# Merhabalar

Bu notta veri bilimi için istatikle ilgili aldığım notlardır. 

İyi okumalar :)

#### Veri Bilimi İçin İstatistik

##### Örnek Teorisi

In [1]:
import numpy as np
populasyon = np.random.randint(0, 90, 100000)
populasyon[0:10]

array([44, 50, 63, 40, 15, 39, 58,  4, 75, 31])

In [2]:
#orneklem çekmek, seed kavramı yapılacak olan işlemin her tekrar edildiğinde aynı sonucu getirmesini sağlar
np.random.seed(10)
orneklem = np.random.choice(a = populasyon, size = 100)
orneklem[0:10]

array([85, 48, 69, 61, 32, 56, 41, 79, 79, 15])

In [3]:
orneklem.mean()

45.36

In [4]:
populasyon.mean()

44.65289

In [5]:
#orneklem dağılımı
np.random.seed(10)
orneklem1 = np.random.choice(a = populasyon, size = 100)
orneklem2= np.random.choice(a = populasyon, size = 100)
orneklem3 = np.random.choice(a = populasyon, size = 100)
orneklem4 = np.random.choice(a = populasyon, size = 100)
orneklem5 = np.random.choice(a = populasyon, size = 100)
orneklem6 = np.random.choice(a = populasyon, size = 100)
orneklem7 = np.random.choice(a = populasyon, size = 100)
orneklem8 = np.random.choice(a = populasyon, size = 100)
orneklem9 = np.random.choice(a = populasyon, size = 100)

In [6]:
(orneklem1.mean() + orneklem2.mean() + orneklem3.mean() + orneklem4.mean() + orneklem5.mean() 
 + orneklem6.mean() + orneklem7.mean() +orneklem8.mean() + orneklem9.mean()) / 9

43.53555555555556

In [7]:
orneklem1.mean()

45.36

In [8]:
orneklem2.mean()

46.48

In [9]:
orneklem3.mean()

46.64

In [10]:
orneklem4.mean()

41.51

In [11]:
orneklem5.mean()

41.76

In [12]:
orneklem6.mean()

40.73

In [13]:
orneklem7.mean()

38.82

In [14]:
orneklem8.mean()

45.67

In [15]:
orneklem9.mean()

44.85

#### Betimsel İstatistikler

In [16]:
import seaborn as sns
tips = sns.load_dataset("tips")
df = tips.copy()
df

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [17]:
df.describe().T

count       mean       std   min      25%     50%      75%    max
total_bill  244.0  19.785943  8.902412  3.07  13.3475  17.795  24.1275  50.81
tip         244.0   2.998279  1.383638  1.00   2.0000   2.900   3.5625  10.00
size        244.0   2.569672  0.951100  1.00   2.0000   2.000   3.0000   6.00

In [18]:
!pip install researchpy

Sayısal değişkenleri göstermek için summery_cont kullanırız

In [19]:
import researchpy as rp
rp.summary_cont(df[["total_bill", "tip", "size"]])

Variable      N     Mean      SD      SE  95% Conf.  Interval
0  total_bill  244.0  19.7859  8.9024  0.5699    18.6633   20.9086
1         tip  244.0   2.9983  1.3836  0.0886     2.8238    3.1728
2        size  244.0   2.5697  0.9511  0.0609     2.4497    2.6896

* Variable : Değişkenler
* N: Gözlem Sayısı
* Mean: Ortalama Değer
* SD: Standart Sapma
* SE: Standaart Hata
* Conf, ınterval: Güven Aralıkları

Kategorik değişkenleri göstermek için summery_cat kullanırız

In [20]:
rp.summary_cat(df[["sex", "smoker", "day"]])

Variable Outcome  Count  Percent
0      sex    Male    157    64.34
1           Female     87    35.66
2   smoker      No    151    61.89
3              Yes     93    38.11
4      day     Sat     87    35.66
5              Sun     76    31.15
6             Thur     62    25.41
7              Fri     19     7.79

#### Kovaryans ve Korelasyon

Kovaryans için

In [21]:
df[["tip", "total_bill"]].cov()

tip  total_bill
tip         1.914455    8.323502
total_bill  8.323502   79.252939

Korelasyon için

In [22]:
df[["tip", "total_bill"]].corr()

tip  total_bill
tip         1.000000    0.675734
total_bill  0.675734    1.000000

#### Fiyat Stratejisi Karar Destek Uygulaması

In [23]:
import numpy as np
fiyatlar = np.random.randint(10, 110, 100)
fiyatlar

array([ 72,  47,  69,  54,  64,  33,  16,  20,  79,  31,  39,  67,  26,
        22, 100,  29,  58,  29,  78,  19,  57,  23,  31,  53,  91, 104,
        77,  85,  52,  62,  98, 101,  52,  78,  14,  96,  61,  40,  63,
        41,  88,  81,  11,  24,  77,  81,  55,  69,  60,  64,  47,  13,
        75,  30,  20,  72, 109,  64,  29,  12,  29, 105,  79,  83, 109,
       105,  11, 103,  24, 103,  24, 106,  18,  98,  72,  14,  94,  19,
        85,  87,  40,  60,  56,  89,  36, 101,  80,  24,  17,  65,  22,
        93,  32,  97,  33,  57,  80, 103,  17,  69])

In [24]:
fiyatlar.mean()

58.51

In [25]:
import statsmodels.stats.api as sms

In [26]:
sms.DescrStatsW(fiyatlar).tconfint_mean()

(52.51696700637287, 64.50303299362713)

#### Olasılık Dağılımları

#### Büyük Sayılar Yasası
Bir rassal değişkenin uzun vadeli kararlılığını tanımlayan olasılık teorimidir

In [27]:
import numpy as np
yazi_tura = np.random.RandomState(123)
for i in np.arange(1,21):
    deney_sayisi = 2**i
    yazi_turalar = yazi_tura.randint(0, 2, size = deney_sayisi)
    yazi_olasiliklari = np.mean(yazi_turalar)
    print("Atış Sayısı:", deney_sayisi, "  " "Yazı Olasılığı: %.2f" %(yazi_olasiliklari * 100))


Atış Sayısı: 2   Yazı Olasılığı: 50.00
Atış Sayısı: 4   Yazı Olasılığı: 0.00
Atış Sayısı: 8   Yazı Olasılığı: 62.50
Atış Sayısı: 16   Yazı Olasılığı: 43.75
Atış Sayısı: 32   Yazı Olasılığı: 46.88
Atış Sayısı: 64   Yazı Olasılığı: 56.25
Atış Sayısı: 128   Yazı Olasılığı: 50.78
Atış Sayısı: 256   Yazı Olasılığı: 52.73
Atış Sayısı: 512   Yazı Olasılığı: 52.93
Atış Sayısı: 1024   Yazı Olasılığı: 50.20
Atış Sayısı: 2048   Yazı Olasılığı: 48.58
Atış Sayısı: 4096   Yazı Olasılığı: 49.49
Atış Sayısı: 8192   Yazı Olasılığı: 49.58
Atış Sayısı: 16384   Yazı Olasılığı: 49.96
Atış Sayısı: 32768   Yazı Olasılığı: 50.00
Atış Sayısı: 65536   Yazı Olasılığı: 49.68
Atış Sayısı: 131072   Yazı Olasılığı: 49.97
Atış Sayısı: 262144   Yazı Olasılığı: 50.13
Atış Sayısı: 524288   Yazı Olasılığı: 50.01
Atış Sayısı: 1048576   Yazı Olasılığı: 50.09


##### Bernoulli Dağılımı

In [28]:
from scipy.stats import bernoulli

In [29]:
yazi = 0.6 #yazi oranı 0.6 olsun

In [30]:
yazi_tura = bernoulli(yazi)
yazi_tura.pmf(k=1)

0.6

In [31]:
yazi_tura = bernoulli(yazi) #tura gelme olasılığı 
yazi_tura.pmf(k=0)

0.4

#### Binom Dağılımı

In [32]:
from scipy.stats import binom

In [33]:
p = 0.01
n= 100
rv = binom(n, p)
print(rv.pmf(1))
print(rv.pmf(5))

0.36972963764971983
0.0028977871237616114


#### Poisson Dağılımı

In [34]:
from scipy.stats import poisson

In [35]:
lambda_ = 0.1

In [36]:
rv = poisson(mu = lambda_)
print(rv.pmf(k = 0))
print(rv.pmf(k = 3))


0.9048374180359595
0.00015080623633932676


#### Normal Dağılım

In [37]:
from scipy.stats import norm

cdf(hesaplamak istediğimiz değeri, ortalama, standart sapma)

90 dan fazla olması ve 70 den fazla olması olasılıklarını değerlendirelim

In [38]:
1-norm.cdf(90, 80, 5)

0.02275013194817921

In [39]:
1-norm.cdf(70, 80, 5)

0.9772498680518208

70 dan az olması ve 80-85 arası olması olasılıklarını değerlendirelim

In [40]:
norm.cdf(70, 80, 5)

0.022750131948179195

In [41]:
norm.cdf(85, 80, 5) - norm.cdf(80, 80, 5)

0.3413447460685429