# Merhabalar

Bu notlarda python numpy kütüphanesinde çalışırken aldığım notlar ve örnekler yer almaktadır.

İyi Gezinmeler :)

#### NumPy kütüphanesi nasıl tanımlanır

In [1]:
import numpy as np

#### NumPy array'i oluşturmak

In [2]:
import numpy as np

In [3]:
liste_1 = np.array([1, 2, 3, 4, 5, 6])
liste_1

array([1, 2, 3, 4, 5, 6])

Listenin type methoduyla tipini sorduğumuzda numpy arrayı olduğunu görebiliriz.

In [4]:
type(liste_1)

numpy.ndarray

Numpy dizileri tek tip veri tuttukları için eğer içerisinde bir tane ondalıklı sayı bulunursa diğer elemanları da ondalıklı olarak yazar.

In [5]:
np.array([1, 2, 3.14, 4, 5.12])

array([1.  , 2.  , 3.14, 4.  , 5.12])

Ondalıklı bir diziyi tam sayı olarak yazdırmak istersek

In [6]:
np.array([1, 2, 3.14, 4, 5.12], dtype = int)

array([1, 2, 3, 4, 5])

In [7]:
import numpy as np

In [8]:
liste_1 = np.array([1, 3, 5, 7])
liste_2 = np.array([2, 4, 6, 8])

In [9]:
liste_1*liste_2

array([ 2, 12, 30, 56])

#### Sıfırdan array oluşturmak

In [10]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Her elemanının bir olması için ones methodunu uygulayabiliriz.

In [11]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

Bir tane 3 satır 5 sütündan oluşan ve her elemanı 3 olan bir matris oluşturalım

In [12]:
np.full((3,5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

Bir tanede doğrusal olarak 9 ar 9 ar artan bir dizi tanımlayalım.

In [13]:
np.arange(0,55, 9)

array([ 0,  9, 18, 27, 36, 45, 54])

Girilen iki değer arasında 10 tane değer oluşturmak istersek

In [14]:
np.linspace(1,5, 10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

Ortalaması 12 standart sapması 4 olan bir matris tasarlayalım.

In [15]:
np.random.normal(12, 4, (4,4))

array([[ 8.13730738, 14.83522004,  6.59227881,  8.03735855],
       [16.90412918,  7.23285342, 18.89330655, 14.04255368],
       [10.17123834, 11.76474867, 20.46042423, 17.31648207],
       [ 8.72317569, 10.90753304,  7.64372988, 11.91530504]])

İnteger değerlerden rastgele bir matris üretmek istersek

In [16]:
np.random.randint(0,10, (4,4))

array([[6, 3, 0, 9],
       [6, 7, 1, 8],
       [6, 6, 7, 4],
       [6, 2, 3, 8]])

* **ndim**: Boyut sayısı
* **shape**: Boyut bilgisi
* **size**: Toplam eleman sayısı
* **dytpe**: Array veri tipi

In [17]:
import numpy as np

Rastgele 10 tane integer değeri oluşturalım

In [18]:
liste_1 = np.random.randint(10, size = 10)
liste_1

array([8, 8, 5, 0, 0, 6, 7, 9, 1, 4])

Boyut sayısını öğrenmek için ndim fonksiyonunu kullanabilirsiniz.

In [19]:
liste_1.ndim

1

Boyut bilgisini öğrenmek için shape fonksiyonunu kullanabilirsiniz.

In [20]:
liste_1.shape

(10,)

10, vermesinin nedeni elimizdeki array tek boyutlu bir dizi olduğu içindir bunu başka bir örnekle 2 boyutlu olarak görelim.

In [21]:
liste_2 = np.random.randint(10, size = (3,5))
liste_2

array([[7, 5, 3, 3, 9],
       [9, 7, 1, 7, 6],
       [7, 7, 0, 6, 4]])

In [22]:
liste_2.ndim

2

In [23]:
liste_2.shape

(3, 5)

b matrisimiz 2 boyutlu olduğundan burada virgülden sonrada bir değer görüyoruz.

Toplam eleman sayısını görmek için size fonksiyonunu kullanalım

In [24]:
liste_1.size

10

In [25]:
liste_2.size

15

Arraylerimizin veri tipini öğrenmek istiyorsak dtype fonksiyonunu kullanbiliriz.

In [26]:
liste_1.dtype

dtype('int32')

In [27]:
liste_2.dtype

dtype('int32')

#### Yeniden Şekillendirme (ReShaping)

Verilen diziyi, vektörü, matrisi başka bir şekile dönüştürme işlemini reshape fonksiyonunu kullanarak yaparız.

In [28]:
import numpy as np

In [29]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
liste_1 = np.arange(1,10)
liste_1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
liste_1.ndim

1

In [33]:
liste_2 = liste_1.reshape(1,9)
liste_2

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [34]:
liste_2.ndim

2

#### Array Birleştirme (Concatenation)

Dizileri veya vektörleri, matrisleri birleştirmek için concatenate fonksiyonunu kullanırız.

In [35]:
import numpy as np

In [36]:
dizi_1 = np.array([1,2,3,4,5])
dizi_2 = np.array([6,7,8,9,10])

In [37]:
np.concatenate([dizi_1, dizi_2])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
dizi_3 = np.array([11,12,13,14,15])

In [39]:
np.concatenate([dizi_1, dizi_2, dizi_3])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [40]:
matris_1 = np.array([[1,2,3], 
                     [3,4,5]])

In [41]:
matris_2 = np.array([[5,6,7], 
                     [7,8,9]])

In [42]:
np.concatenate([matris_1, matris_2])

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7],
       [7, 8, 9]])

Satır bazında değilde sütün bazında değiştirmek istersek axis kullanırız 0 satırı 1 sütünü ifade eder.

In [43]:
np.concatenate([matris_1, matris_2], axis = 0)

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7],
       [7, 8, 9]])

In [44]:
np.concatenate([matris_1, matris_2], axis = 1)

array([[1, 2, 3, 5, 6, 7],
       [3, 4, 5, 7, 8, 9]])

#### Array Ayırma (Splitting)

Dizileri veya vektörleri, matrisleri ayırmak için split fonksiyonunu kullanırız.

In [45]:
import numpy as np

In [46]:
dizi_1 = np.array([1,2,3,4,99,99,99,99,4,3,2,1])
dizi_1

array([ 1,  2,  3,  4, 99, 99, 99, 99,  4,  3,  2,  1])

In [47]:
np.split(dizi_1, [4,8])

[array([1, 2, 3, 4]), array([99, 99, 99, 99]), array([4, 3, 2, 1])]

Bu dizileri ayrı ayrı diziler haline getirmek istersek.

In [48]:
ayrilan_dizi_1, ayrilan_dizi_2, ayrilan_dizi_3 = np.split(dizi_1, [4,8])

In [49]:
ayrilan_dizi_1

array([1, 2, 3, 4])

In [50]:
ayrilan_dizi_2

array([99, 99, 99, 99])

In [51]:
ayrilan_dizi_3

array([4, 3, 2, 1])

In [52]:
a = np.arange(25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [53]:
np.vsplit(a, [1,2,3,4])

[array([[0, 1, 2, 3, 4]]),
 array([[5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19]]),
 array([[20, 21, 22, 23, 24]])]

In [54]:
bir, iki, uc, dort, bes = np.vsplit(a, [1,2,3,4])

In [55]:
bir

array([[0, 1, 2, 3, 4]])

In [56]:
iki

array([[5, 6, 7, 8, 9]])

In [57]:
uc

array([[10, 11, 12, 13, 14]])

In [58]:
dort

array([[15, 16, 17, 18, 19]])

In [59]:
bes

array([[20, 21, 22, 23, 24]])

In [60]:
np.vsplit(a, [3])

[array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]])]

In [61]:
uc_alt, uc_ust = np.vsplit(a, [3])

In [62]:
uc_alt

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [63]:
uc_ust

array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [64]:
np.hsplit(a, [3])

[array([[ 0,  1,  2],
        [ 5,  6,  7],
        [10, 11, 12],
        [15, 16, 17],
        [20, 21, 22]]),
 array([[ 3,  4],
        [ 8,  9],
        [13, 14],
        [18, 19],
        [23, 24]])]

In [65]:
dikey_1, dikey_2 = np.hsplit(a, [3])

In [66]:
dikey_1

array([[ 0,  1,  2],
       [ 5,  6,  7],
       [10, 11, 12],
       [15, 16, 17],
       [20, 21, 22]])

In [67]:
dikey_2

array([[ 3,  4],
       [ 8,  9],
       [13, 14],
       [18, 19],
       [23, 24]])

#### Array Sıralama (Sorting)

Dizideki elemanları sıralamak için sort fonkisyonu kullanırız.

In [68]:
import numpy as np

In [69]:
dizi_1 = np.array([3,67,2,43,9,5,12,4,1,88,24,31,7,56,43,6,78,1])
dizi_1

array([ 3, 67,  2, 43,  9,  5, 12,  4,  1, 88, 24, 31,  7, 56, 43,  6, 78,
        1])

In [70]:
np.sort(dizi_1)

array([ 1,  1,  2,  3,  4,  5,  6,  7,  9, 12, 24, 31, 43, 43, 56, 67, 78,
       88])

In [71]:
dizi_1

array([ 3, 67,  2, 43,  9,  5, 12,  4,  1, 88, 24, 31,  7, 56, 43,  6, 78,
        1])

In [72]:
dizi_2 = np.random.normal(10,3, (4,4))
dizi_2

array([[12.97588371, 10.293762  ,  6.57348371,  6.84544859],
       [10.40012297, 12.07975701,  5.68412043,  9.35119593],
       [13.18587459, 11.77386694,  4.76816881,  6.051103  ],
       [10.42867229,  9.19304581, 12.59195876, 16.93338219]])

Sütünsal olarak sıralamak istersek

In [73]:
np.sort(dizi_2 ,axis = 0)

array([[10.40012297,  9.19304581,  4.76816881,  6.051103  ],
       [10.42867229, 10.293762  ,  5.68412043,  6.84544859],
       [12.97588371, 11.77386694,  6.57348371,  9.35119593],
       [13.18587459, 12.07975701, 12.59195876, 16.93338219]])

Satırsal olarak sıralamak istersek

In [74]:
np.sort(dizi_2 ,axis = 1)

array([[ 6.57348371,  6.84544859, 10.293762  , 12.97588371],
       [ 5.68412043,  9.35119593, 10.40012297, 12.07975701],
       [ 4.76816881,  6.051103  , 11.77386694, 13.18587459],
       [ 9.19304581, 10.42867229, 12.59195876, 16.93338219]])

#### Index ile Elemanlara Erişmek

In [75]:
import numpy as np
a = np.random.randint(10, size = (4,4))
a

array([[1, 1, 0, 1],
       [9, 7, 4, 8],
       [6, 4, 2, 2],
       [1, 8, 0, 8]])

In [76]:
a[1,1]

7

In [77]:
a[2,3] = 53
a

array([[ 1,  1,  0,  1],
       [ 9,  7,  4,  8],
       [ 6,  4,  2, 53],
       [ 1,  8,  0,  8]])

#### Slicing ile Elemanlara Erişmek

Dizilerin alt kümelerine erişmek için slice fonksiyonu kullanırız.

In [78]:
import numpy as np 
a = np.arange(10,20)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [79]:
a[0::2]

array([10, 12, 14, 16, 18])

In [80]:
a[:5]

array([10, 11, 12, 13, 14])

In [81]:
a[5:]

array([15, 16, 17, 18, 19])

In [82]:
a[2:7]

array([12, 13, 14, 15, 16])

In [83]:
a = np.random.randint(10, size = (4,4))
a

array([[7, 6, 7, 2],
       [3, 9, 6, 6],
       [2, 8, 3, 9],
       [9, 9, 4, 9]])

In [84]:
a[:,3]

array([2, 6, 9, 9])

In [85]:
a[3,:]

array([9, 9, 4, 9])

In [86]:
a[3]

array([9, 9, 4, 9])

In [87]:
a[1:3, :3]

array([[3, 9, 6],
       [2, 8, 3]])

In [88]:
a[1:, 0:4]

array([[3, 9, 6, 6],
       [2, 8, 3, 9],
       [9, 9, 4, 9]])

In [89]:
a[3:, 3:]

array([[9]])

In [90]:
a[::, :3]

array([[7, 6, 7],
       [3, 9, 6],
       [2, 8, 3],
       [9, 9, 4]])

In [91]:
a[:4, :4]

array([[7, 6, 7, 2],
       [3, 9, 6, 6],
       [2, 8, 3, 9],
       [9, 9, 4, 9]])

In [92]:
a[::, ::]

array([[7, 6, 7, 2],
       [3, 9, 6, 6],
       [2, 8, 3, 9],
       [9, 9, 4, 9]])

In [93]:
a[0:, ::]

array([[7, 6, 7, 2],
       [3, 9, 6, 6],
       [2, 8, 3, 9],
       [9, 9, 4, 9]])

In [94]:
a[2:4, 1:2]

array([[8],
       [9]])

#### Alt Küme Üzerinde İşlem Yapmak

In [95]:
import numpy as np 
a = np.random.randint(10, size = (5,5) )
a

array([[2, 0, 6, 3, 2],
       [2, 6, 3, 2, 9],
       [4, 9, 6, 7, 3],
       [3, 1, 3, 9, 7],
       [1, 6, 0, 6, 8]])

In [96]:
alt_1 = a[1:4, 2:5]
alt_1

array([[3, 2, 9],
       [6, 7, 3],
       [3, 9, 7]])

In [97]:
alt_1 [1,2] = 53
alt_1 [2,1] = 35
alt_1

array([[ 3,  2,  9],
       [ 6,  7, 53],
       [ 3, 35,  7]])

In [98]:
a

array([[ 2,  0,  6,  3,  2],
       [ 2,  6,  3,  2,  9],
       [ 4,  9,  6,  7, 53],
       [ 3,  1,  3, 35,  7],
       [ 1,  6,  0,  6,  8]])

In [99]:
b = np.random.randint(10, size = (5,5))
b

array([[1, 7, 6, 3, 7],
       [7, 1, 0, 0, 1],
       [6, 6, 1, 6, 3],
       [5, 5, 4, 7, 5],
       [4, 2, 1, 7, 6]])

Copy fonksiyonu arrayın sonuna koyduğumuzda seçmiş olduğumuz alt kümeyi ana arrayden bağımsızlaştırır.

In [100]:
alt_2 = b[1:4, 2:5].copy()
alt_2

array([[0, 0, 1],
       [1, 6, 3],
       [4, 7, 5]])

In [101]:
alt_2 [1,2] = 53
alt_2 [2,1] = 35
alt_2

array([[ 0,  0,  1],
       [ 1,  6, 53],
       [ 4, 35,  5]])

Ana fonksiyonda herhangi bir değişme olmadı.

In [102]:
b

array([[1, 7, 6, 3, 7],
       [7, 1, 0, 0, 1],
       [6, 6, 1, 6, 3],
       [5, 5, 4, 7, 5],
       [4, 2, 1, 7, 6]])

#### Fancy Index ile Elemanlara Erişmek

In [103]:
import numpy as np
a = np.arange(0, 32, 3)
a

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [104]:
[a[1], a[3], a[5], a[7]]

[3, 9, 15, 21]

In [105]:
fancy = [1,3,5,7]
a[fancy]

array([ 3,  9, 15, 21])

In [106]:
b = np.arange(9).reshape((3,3))
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [107]:
satir = np.array([2,1])
sutun = np.array([1,0])
b[satir,sutun]

array([7, 3])

#### Koşullu Eleman İşlemleri

In [108]:
import numpy as np
a = np.array([1,2,3,4,5,6,7,8])
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [109]:
a <= 5

array([ True,  True,  True,  True,  True, False, False, False])

In [110]:
a[a <= 5]

array([1, 2, 3, 4, 5])

In [111]:
a[a >= 8]

array([8])

In [112]:
a[a == 6]

array([6])

In [113]:
a[a != 4]

array([1, 2, 3, 5, 6, 7, 8])

#### Matematiksel İşlemler

In [114]:
import numpy as np
a = np.array([1,2,3,4,5,6,7,8])
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [115]:
a * 2

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [116]:
a / 3

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667,
       2.        , 2.33333333, 2.66666667])

In [117]:
a*5/2

array([ 2.5,  5. ,  7.5, 10. , 12.5, 15. , 17.5, 20. ])

In [118]:
a**3/2

array([  0.5,   4. ,  13.5,  32. ,  62.5, 108. , 171.5, 256. ])

In [119]:
a % 2

array([1, 0, 1, 0, 1, 0, 1, 0], dtype=int32)

In [120]:
a - 1 

array([0, 1, 2, 3, 4, 5, 6, 7])

In [121]:
np.subtract(a, 2)

array([-1,  0,  1,  2,  3,  4,  5,  6])

In [122]:
np.add(a, 4)

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [123]:
np.multiply(a, 5)

array([ 5, 10, 15, 20, 25, 30, 35, 40])

In [124]:
np.divide(a, 2)

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [125]:
np.power(a, 3)

array([  1,   8,  27,  64, 125, 216, 343, 512], dtype=int32)

In [126]:
np.mod(a, 2)

array([1, 0, 1, 0, 1, 0, 1, 0], dtype=int32)

In [127]:
np.absolute(np.array([-3]))

array([3])

In [128]:
np.sin(360)

0.9589157234143065

In [129]:
np.sin(180)

-0.8011526357338304

In [130]:
np.cos(360)

-0.2836910914865273

In [131]:
np.cos(180)

-0.5984600690578581

In [132]:
a = np.array([1,2,3,4,5])

In [133]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [134]:
np.log2(a)

array([0.        , 1.        , 1.5849625 , 2.        , 2.32192809])

In [135]:
np.log10(a)

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ])

In [136]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [137]:
np.exp(a)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

#### İki Bilinmeyenli Denklem Çözümü

4 * x0 + x1 = 17

x0 + 6 * x1 = 9

In [138]:
import numpy as np
a = np.array([[4, 1], [1, 6]])
b = np.array([17,9])

In [139]:
a

array([[4, 1],
       [1, 6]])

In [140]:
b

array([17,  9])

In [141]:
c = np.linalg.solve(a, b)
c

array([4.04347826, 0.82608696])