# Merhabalar

Bu notlarda python numpy kütüphanesinde çalışırken aldığım notlar ve örnekler yer almaktadır.

İyi Gezinmeler :)

#### NumPy kütüphanesi nasıl tanımlanır

In [51]:
import numpy as np

#### NumPy array'i oluşturmak

In [52]:
import numpy as np

In [53]:
liste_1 = np.array([1, 2, 3, 4, 5, 6])
liste_1

array([1, 2, 3, 4, 5, 6])

Listenin type methoduyla tipini sorduğumuzda numpy arrayı olduğunu görebiliriz.

In [54]:
type(liste_1)

numpy.ndarray

Numpy dizileri tek tip veri tuttukları için eğer içerisinde bir tane ondalıklı sayı bulunursa diğer elemanları da ondalıklı olarak yazar.

In [55]:
np.array([1, 2, 3.14, 4, 5.12])

array([1.  , 2.  , 3.14, 4.  , 5.12])

Ondalıklı bir diziyi tam sayı olarak yazdırmak istersek

In [56]:
np.array([1, 2, 3.14, 4, 5.12], dtype = int)

array([1, 2, 3, 4, 5])

In [57]:
import numpy as np

In [58]:
liste_1 = np.array([1, 3, 5, 7])
liste_2 = np.array([2, 4, 6, 8])

In [59]:
liste_1*liste_2

array([ 2, 12, 30, 56])

#### Sıfırdan array oluşturmak

In [60]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Her elemanının bir olması için ones methodunu uygulayabiliriz.

In [61]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

Bir tane 3 satır 5 sütündan oluşan ve her elemanı 3 olan bir matris oluşturalım

In [62]:
np.full((3,5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

Bir tanede doğrusal olarak 9 ar 9 ar artan bir dizi tanımlayalım.

In [63]:
np.arange(0,55, 9)

array([ 0,  9, 18, 27, 36, 45, 54])

Girilen iki değer arasında 10 tane değer oluşturmak istersek

In [64]:
np.linspace(1,5, 10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

Ortalaması 12 standart sapması 4 olan bir matris tasarlayalım.

In [69]:
np.random.normal(12, 4, (4,4))

array([[12.03117196,  2.557449  , 15.44109449,  9.41463896],
       [12.5338679 , 14.82790169, 13.2889221 , 15.47667875],
       [14.9404823 ,  8.78577504, 12.91146993, 13.74108894],
       [ 9.8401159 , 22.22857743, 16.04461388,  9.50538476]])

İnteger değerlerden rastgele bir matris üretmek istersek

In [71]:
np.random.randint(0,10, (4,4))

array([[4, 1, 8, 8],
       [2, 7, 9, 1],
       [2, 7, 8, 9],
       [8, 6, 9, 4]])

* **ndim**: Boyut sayısı
* **shape**: Boyut bilgisi
* **size**: Toplam eleman sayısı
* **dytpe**: Array veri tipi

In [95]:
import numpy as np

Rastgele 10 tane integer değeri oluşturalım

In [96]:
liste_1 = np.random.randint(10, size = 10)
liste_1

array([0, 6, 4, 1, 1, 9, 4, 4, 3, 7])

Boyut sayısını öğrenmek için ndim fonksiyonunu kullanabilirsiniz.

In [97]:
liste_1.ndim

1

Boyut bilgisini öğrenmek için shape fonksiyonunu kullanabilirsiniz.

In [98]:
liste_1.shape

(10,)

10, vermesinin nedeni elimizdeki array tek boyutlu bir dizi olduğu içindir bunu başka bir örnekle 2 boyutlu olarak görelim.

In [105]:
liste_2 = np.random.randint(10, size = (3,5))
liste_2

array([[3, 1, 2, 8, 6],
       [4, 7, 5, 4, 4],
       [4, 3, 2, 5, 7]])

In [111]:
liste_2.ndim

2

In [112]:
liste_2.shape

(3, 5)

b matrisimiz 2 boyutlu olduğundan burada virgülden sonrada bir değer görüyoruz.

Toplam eleman sayısını görmek için size fonksiyonunu kullanalım

In [113]:
liste_1.size

10

In [114]:
liste_2.size

15

Arraylerimizin veri tipini öğrenmek istiyorsak dtype fonksiyonunu kullanbiliriz.

In [117]:
liste_1.dtype

dtype('int32')

In [118]:
liste_2.dtype

dtype('int32')

#### Yeniden Şekillendirme (ReShaping)

Verilen diziyi, vektörü, matrisi başka bir şekile dönüştürme işlemini reshape fonksiyonunu kullanarak yaparız.

In [ ]:
import numpy as np

In [119]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [132]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [133]:
liste_1 = np.arange(1,10)
liste_1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [134]:
liste_1.ndim

1

In [135]:
liste_2 = liste_1.reshape(1,9)
liste_2

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [136]:
liste_2.ndim

2

#### Array Birleştirme (Concatenation)

Dizileri veya vektörleri, matrisleri birleştirmek için concatenate fonksiyonunu kullanırız.

In [139]:
import numpy as np

In [140]:
dizi_1 = np.array([1,2,3,4,5])
dizi_2 = np.array([6,7,8,9,10])

In [141]:
np.concatenate([dizi_1, dizi_2])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [142]:
dizi_3 = np.array([11,12,13,14,15])

In [143]:
np.concatenate([dizi_1, dizi_2, dizi_3])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [168]:
matris_1 = np.array([[1,2,3], 
                     [3,4,5]])

In [169]:
matris_2 = np.array([[5,6,7], 
                     [7,8,9]])

In [170]:
np.concatenate([matris_1, matris_2])

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7],
       [7, 8, 9]])

Satır bazında değilde sütün bazında değiştirmek istersek axis kullanırız 0 satırı 1 sütünü ifade eder.

In [173]:
np.concatenate([matris_1, matris_2], axis = 0)

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7],
       [7, 8, 9]])

In [174]:
np.concatenate([matris_1, matris_2], axis = 1)

array([[1, 2, 3, 5, 6, 7],
       [3, 4, 5, 7, 8, 9]])

#### Array Ayırma (Splitting)

Dizileri veya vektörleri, matrisleri ayırmak için split fonksiyonunu kullanırız.

In [ ]:
import numpy as np

In [175]:
dizi_1 = np.array([1,2,3,4,99,99,99,99,4,3,2,1])
dizi_1

array([ 1,  2,  3,  4, 99, 99, 99, 99,  4,  3,  2,  1])

In [176]:
np.split(dizi_1, [4,8])

[array([1, 2, 3, 4]), array([99, 99, 99, 99]), array([4, 3, 2, 1])]

Bu dizileri ayrı ayrı diziler haline getirmek istersek.

In [181]:
ayrilan_dizi_1, ayrilan_dizi_2, ayrilan_dizi_3 = np.split(dizi_1, [4,8])

In [182]:
ayrilan_dizi_1

array([1, 2, 3, 4])

In [183]:
ayrilan_dizi_2

array([99, 99, 99, 99])

In [184]:
ayrilan_dizi_3

array([4, 3, 2, 1])

In [185]:
a = np.arange(25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [191]:
np.vsplit(a, [1,2,3,4])

[array([[0, 1, 2, 3, 4]]),
 array([[5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19]]),
 array([[20, 21, 22, 23, 24]])]

In [193]:
bir, iki, uc, dort, bes = np.vsplit(a, [1,2,3,4])

In [194]:
bir

array([[0, 1, 2, 3, 4]])

In [195]:
iki

array([[5, 6, 7, 8, 9]])

In [196]:
uc

array([[10, 11, 12, 13, 14]])

In [197]:
dort

array([[15, 16, 17, 18, 19]])

In [198]:
bes

array([[20, 21, 22, 23, 24]])

In [200]:
np.vsplit(a, [3])

[array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]])]

In [202]:
uc_alt, uc_ust = np.vsplit(a, [3])

In [203]:
uc_alt

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [204]:
uc_ust

array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [210]:
np.hsplit(a, [3])

[array([[ 0,  1,  2],
        [ 5,  6,  7],
        [10, 11, 12],
        [15, 16, 17],
        [20, 21, 22]]),
 array([[ 3,  4],
        [ 8,  9],
        [13, 14],
        [18, 19],
        [23, 24]])]

In [211]:
dikey_1, dikey_2 = np.hsplit(a, [3])

In [212]:
dikey_1

array([[ 0,  1,  2],
       [ 5,  6,  7],
       [10, 11, 12],
       [15, 16, 17],
       [20, 21, 22]])

In [213]:
dikey_2

array([[ 3,  4],
       [ 8,  9],
       [13, 14],
       [18, 19],
       [23, 24]])

#### Array Sıralama (Sorting)

Dizideki elemanları sıralamak için sort fonkisyonu kullanırız.

In [ ]:
import numpy as np

In [214]:
dizi_1 = np.array([3,67,2,43,9,5,12,4,1,88,24,31,7,56,43,6,78,1])
dizi_1

array([ 3, 67,  2, 43,  9,  5, 12,  4,  1, 88, 24, 31,  7, 56, 43,  6, 78,
        1])

In [215]:
np.sort(dizi_1)

array([ 1,  1,  2,  3,  4,  5,  6,  7,  9, 12, 24, 31, 43, 43, 56, 67, 78,
       88])

In [216]:
dizi_1

array([ 3, 67,  2, 43,  9,  5, 12,  4,  1, 88, 24, 31,  7, 56, 43,  6, 78,
        1])

In [219]:
dizi_2 = np.random.normal(10,3, (4,4))
dizi_2

array([[11.61143276, 13.35939027,  7.78437036, 18.19261969],
       [11.28518088, 13.07510514,  1.44350503, 12.3320821 ],
       [10.31375041, 10.97334509, 12.94860569, 12.92799566],
       [ 9.47746282, 12.20737346, 10.35454483,  4.43147453]])

Sütünsal olarak sıralamak istersek

In [224]:
np.sort(dizi_2 ,axis = 0)

array([[ 9.47746282, 10.97334509,  1.44350503,  4.43147453],
       [10.31375041, 12.20737346,  7.78437036, 12.3320821 ],
       [11.28518088, 13.07510514, 10.35454483, 12.92799566],
       [11.61143276, 13.35939027, 12.94860569, 18.19261969]])

Satırsal olarak sıralamak istersek

In [225]:
np.sort(dizi_2 ,axis = 1)

array([[ 7.78437036, 11.61143276, 13.35939027, 18.19261969],
       [ 1.44350503, 11.28518088, 12.3320821 , 13.07510514],
       [10.31375041, 10.97334509, 12.92799566, 12.94860569],
       [ 4.43147453,  9.47746282, 10.35454483, 12.20737346]])

#### Index ile Elemanlara Erişmek

In [230]:
import numpy as np
a = np.random.randint(10, size = (4,4))
a

array([[3, 7, 5, 4],
       [3, 1, 4, 1],
       [9, 8, 1, 1],
       [9, 9, 7, 3]])

In [231]:
a[1,1]

3